# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-20 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_B', models.FloatField()),
                ('coord_L', models.FloatField()),
                ('coord_H', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_rise', models.TimeField()),
                ('time_set', models.TimeField()),
            ],
        ),
    ]
