# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='coord_B',
            field=models.CharField(default='55°45′07″', max_length=10),
        ),
        migrations.AlterField(
            model_name='coords',
            name='coord_H',
            field=models.FloatField(default=144),
        ),
        migrations.AlterField(
            model_name='coords',
            name='coord_L',
            field=models.TextField(default='37°36′56″', max_length=10),
        ),
    ]
