# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0002_auto_20170425_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='coord_L',
            field=models.CharField(default='37°36′56″', max_length=10),
        ),
    ]
