# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0002_sun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_B', models.FloatField()),
                ('coord_L', models.FloatField()),
                ('coord_H', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Cords',
        ),
    ]
