# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0003_auto_20170419_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='coords',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 20, 11, 46, 1, 175092)),
        ),
    ]
