# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0003_auto_20170425_1621'),
        ('WhetherDawnUp', '0002_auto_20170425_2225'),
    ]

    operations = [
    ]
