# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-27 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0004_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coords',
        ),
        migrations.DeleteModel(
            name='Sun',
        ),
    ]
