# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0005_auto_20170420_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
