# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0006_auto_20170420_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
