# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhetherDawnUp', '0007_auto_20170420_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
